### ISSUE TITLE
What is the difference between spop and spotifyd

### ISSUE THREAD

**Issue by mib4fun** [Schnouki/spop#65]
Hello,

Maybe a noob question.
Can you explain to me the differences between your library spop and https://github.com/Spotifyd/spotifyd ?

**Comment by Schnouki** [comment]
Hi,

Good question actually.
- spop is based on libspotify, spotifyd is based on [librespot](https://github.com/plietar/librespot)
- spop can be controlled using its own API; spotifyd can be controlled by the official Spotify application through the Spotify Connect protocol (although there's [spotifyd-http](https://github.com/Spotifyd/spotifyd-http) which should allow for something similar to spop, but I'm not sure it works)
- because of this, spop can be used and controlled without depending on an official Spotify client (on desktop or mobile device). I use it on my laptop with a few keyboard shortcuts and the "dspop" client. I don't think this would be possible with spotifyd at the moment.
- libspotify, the "official" Spotify library, is considered deprecated and may stop working at any moment. When this happens (and I say *when*, not *if*), spop will stop working forever.
- librespot was designed by reverse-engineering the official Spotify clients, which may or may not be legal (in some countries) or allowed by the Spotify terms of service.

At the moment, depending on your use case, I think you can use either one or the other. When libspotify stops working on the other hand, there will only be spotifyd (or other clients based on librespot) until someone comes up with another solution...
